name: project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.2.3
  path_provider: any
  http: ^0.13.5 
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  provider: ^6.1.1 
  flutter_svg: ^2.0.9 
  flutter_facebook_auth: ^6.0.3
  font_awesome_flutter: ^10.6.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  toggle_switch: ^2.1.0  
  syncfusion_flutter_sliders: ^24.2.3  
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  google_sign_in: ^6.2.1
  flutter_toggle_tab: ^1.4.1
  dropdown_button2: ^2.3.9
  form_field_validator: ^1.1.0
  validation_textformfield: ^2.2.5
  google_maps_flutter: ^2.5.3
  flutter_launcher_icons: ^0.13.1
  geolocator: ^10.1.0
  excel: ^4.0.2
  material_floating_search_bar_2: ^0.5.0
  search_map_location: ^0.0.6
  url_launcher: ^6.0.12
  location: ^5.0.3

  #icon
  line_awesome_flutter: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets_images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: "assets_images/Logo ccp.png" # Replace with the path to your custom logo
